### PR TITLE
WIP: Splitting locales into individual files

### PR DESCRIPTION
**Pull request by radar**

### CODE REVIEW

**Comment by radar** [comment]
Thanks for the suggestions @styd. I agree that we could probably move the negative checking out to a common method. 

I have moved the `stringify` method out to the `Humanize` module itself.

I've gone ahead and done the `fr`, `tr` and `az` locales, but I'm currently running into a bug with the `id` locale:

```
 1) Humanize locale option indonesian specific rules one thousand equals "satu ribu" when it is not the only thousand in its thousands range
     Failure/Error: expect(1_101_000.humanize).to eql('satu juta seratus satu ribu')

       expected: "satu juta seratus satu ribu"
            got: "satu juta seratus satu ribu nol"

       (compared using eql?)
     # ./spec/humanize_spec.rb:54:in `block (5 levels) in <top (required)>'
     # ./spec/spec_helper.rb:8:in `block (2 levels) in <top (required)>'
```

I don't speak or even understand indonesian, so I am not sure what is happening here.

Do you have some time to investigate this for me, @styd?

**Comment by styd** [comment]
I'll try to investigate this tonight, @radar. It's still 8:40 am here.

**Comment by styd** [comment]
@radar, I guess you forgot the `unless remainder.zero?` condition when appending `SUB_ONE_GROUPING[remainder]` to `output`.

**Comment by radar** [comment]
Thank you @styd. That was indeed the issue. I will add tests for this to all the locales tomorrow.

I have one locale to go (th) and then I think we're good. 

Next steps for me are to implement that th locale, and then to code review this PR myself. Would love if you could take a look next week too!

**Comment by radar** [comment]
I'm finished + happy with this branch now. I've done a review tonight on it and I think it's fine. If there's no dissenting voices by next week, I'll be merging it into master and releasing it as humanize 2.0

**Comment by styd** [comment]
It looks neat to me. I think you did a great job refactoring it, @radar.

**Comment by radar** [comment]
I'm merging this tonight and will be releasing humanize 2.0 imminently.

**Comment by radar** [comment]
2.0.0 is now available on RubyGems: https://rubygems.org/gems/humanize/versions/2.0.0

**Pull request merged**
