### PR TITLE
Added Spanish translation. But don't work correctly for this language

### PR DESCRIPTION
**Pull request by matiasmasca**
I translated the numbers to the Spanish language, add the locale rule and some test. But it doesn't work fine see the test:
1500.humanize(locale: :es) should be "mil quinientos ochenta y ocho" not "uno mil, quinientos ochenta y ocho" (uno and comma are wrong)

### CODE REVIEW

**Comment by radar** [comment]
My rudimentary understanding of Spanish says that 1500 should be “mil quinentos”. I think your translation is correct for 1508 — but Google Translate says it’s without “y”. I’m not a native speaker, so I’m not sure of the correct translation.

**Comment by radar** [comment]
Whoops, I plugged “one thousand five hundred and eight” into GT. I missed the eighty. Your translation is correct.

**Comment by matiasmasca** [comment]
Sorry, I wrote bad my example, the correct is 1588.
The correct translation has to be "mil quinientos ocheta y ocho", but now the result is "uno mil, quinientos ochenta y ocho "

1500.humanize(locale: :es) has to be "mil quinientos"

1000.humanize(locale: :es) has to be "mil"

I'm spanish native speaker from Argentina

**Comment by matiasmasca** [comment]
The results with Humanize were:
1588.humanize(locale: :es)  => "uno mil, quinientos ochenta y ocho" instead of "mil quinientos ochenta y ocho"
1500.humanize(locale: :es)  => "uno mil, quinientos" instead of "mil quinientos"
1000.humanize(locale: :es) => "uno mil" instead of "mil"

Those "uno" and the comma before de 'mil' are wrong.

**Comment by radar** [comment]
I think the best way to approach this is going to be to split the one `humanize` function into many. We have already special cased it for French and Turkish (iirc), and doing so for Spanish would be probably a step too far.

I think having a per-locale `humanize` function would be more sensible. I have some WIP work in #47 along these lines, but I am out of time for this today.

**Comment by radar** [comment]
I’ve made further progress on #47 today. I think it is almost ready for merging. It will become the 2.0 release of humanize.

Please update your branch to be based off that one, and then follow the conventions in that branch for providing translations.

Thanks!

**Comment by javierav** [comment]
@radar I think that this merge is superseeded by merge #63 that already merged and can be closed!

**Pull request closed without merging**
