### PR TITLE
es locale support

### PR DESCRIPTION
**Pull request by fercreek**
This is my contribution, I will use this gem, so I will add more test cases in a few days.

### CODE REVIEW

**Comment by radar** [comment]
Hi @fercreek could you please resolve the conflicts here?

**Comment by fercreek** [comment]
@radar It´s done! Sorry for the delay

**Comment by fercreek** [comment]
I

**Comment by radar** [comment]
Thank you :)

**Comment by radar** [comment]
I have just pushed 2.3.0 with these changes.

**Comment by fercreek** [comment]
Close https://github.com/radar/humanize/issues/62

**Pull request merged**
